### ISSUE TITLE
"sizeEq" and "sizeNe" as Querycriteria not working

### ISSUE THREAD

**Issue by dtamm** [fabiooshiro/plastic-criteria#18]
The querie criterias "sizeEq" and "sizeNe" are missing in "theImplementations".

**Comment by fabiooshiro** [comment]
You are a smart!
And I'm a lazy, this plugin grows up as needed.

So, try the 1.6.1

**Comment by dtamm** [comment]
Already did :-) thanks, works! I am still working on my PR for #16. also got some more errors when going through joins then 1:n-relations, which affects the implementation of "eq" in "theImplementations".
