### ISSUE TITLE
Grails 3 support

### ISSUE THREAD

**Issue by tbuchwalter** [fabiooshiro/plastic-criteria#25]
This isn't an issue so much as a question.  I have used this plugin in a Grails 2.1.1 application, but I'm now writing an application in Grails 3.2.2 but when I try to add `test ":plastic-criteria:1.6.1"` to my gradle file it is not able to find the plugin.

Am I looking in the wrong place or are there not plans to update the plugin to grails 3?

**Comment by tbuchwalter** [comment]
**For what its worth.**  I'm not experienced with creating plugins, however, I forked the project.  Tried to follow grails 3 documentation for upgrading plugins, but was unable to get it to compile correctly. (I may have done something wrong somewhere)  I was however, able to copy PlasticCriteria.groovy and SaitPeter.groovy into my current project and use it like I have used it in my Grails 2.x applications.  So I believe that an upgrade to Grails 3 is possible, I'm just not skilled enough to do it myself

**Comment by fabiooshiro** [comment]
I will try...
Has grails 3 native support for unit test criteria?

Em 8 de jul de 2017 9:58 AM, "tbuchwalter" <notifications@github.com>
escreveu:

**Comment by tbuchwalter** [comment]
That I'm not sure.  I know that from what I was trying to do, the developers for 
"rest-client-builder" suggested that 

> For Grails 3.x this plugin is no longer necessary and you should instead just declare a dependency on the core Grails Data library:
>
>compile 'org.grails:grails-datastore-rest-client:5.0.0.RC2

and the release plugin did not appear to have grails 3 support (but it might not be needed anyway)

Grails 3 does however incorporate Spock Specification as a bundled unit testing framework and have built HibernateSpec class to work with requesting Domain Classes with simple list, get functionality.

But as I said, Your two main classes appear to work fine as independent classes in my project solution.
I don't know if that answers your question or not.

**Comment by fabiooshiro** [comment]
Hi,

I follow the grails 3 plugin tutorial and got stucked here:
```sh
* What went wrong:
Execution failed for task ':publishMavenPublicationToMavenLocal'.
> Failed to publish publication 'maven' to repository 'mavenLocal'
   > Invalid publication 'maven': artifact file does not exist: '/home/ivt/investtools/no-surprises/build/classes/java/main/META-INF/grails-plugin.xml'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 1s
11 actionable tasks: 2 executed, 9 up-to-date
```
https://github.com/fabiooshiro/no-surprises

**Comment by tbuchwalter** [comment]
I cloned that project and imported into intellij.  I altered the gradle.build file just slightly and was able to build the application.  However, I was not able to get any of the test to run.

I attempted to create a pull request, but I didn't have access to push my branch to you.

**Comment by fabiooshiro** [comment]
Grails 3 support will be realized in another project
https://github.com/fabiooshiro/no-surprises
